require: rubocop-rspec

AllCops:
  NewCops: enable

Lint/MissingSuper:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false
  